# Generated by Django 5.1.6 on 2025-02-15 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
