# Generated by Django 5.1.6 on 2025-02-15 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_product_is_sale_product_sale_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="is_sale",
            new_name="is_onsale",
        ),
    ]
