# Generated by Django 5.1.6 on 2025-02-24 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "shipping Address"},
        ),
    ]
